
All: sbi

sbi: sbi.scm
	./unit_tests.scm test.sbir

submit: README sbi.scm
	submit cmps112-wm.f15 asg1 README sbi.scm
	ls -la /afs/cats.ucsc.edu/class/cmps112-wm.f15/asg1/aaguil10
#REMENBER TO REMOVE UNIT TESTS!!!!!!
 
