#!/bin/sh -x
# $Id: Check,v 1.1 2011-03-24 17:25:20-07 - - $
pmake     >hello.log 2>&1
rm hello
make      >hello.m.log 2>&1
rm hello
diff hello.log hello.m.log
pmake bad >bad.log 2>&1
make bad >bad.m.log 2>&1
diff bad.log bad.m.log 
#pmake
#pmake bad
