#!/bin/sh -x
# $Id: Check,v 1.1 2011-03-24 17:24:36-07 - - $
pmake spotless    >spotless.log 2>&1
make 		  >trash.log 2>&1
make spotless    >spotless.m.log 2>&1
diff spotless.log spotless.m.log

pmake ci          >ci.log 2>&1
make ci          >ci.m.log 2>&1
diff ci.log ci.m.log

make >trash.log 2>&1
pmake             >all.log 2>&1
make >trash.log 2>&1
make              >all.m.log 2>&1
diff all.log all.m.log

#pmake -n spotless
#pmake -n ci
#pmake -n
